### ISSUE TITLE
Allow file upload pass-through to media service

### ISSUE THREAD

**Issue by shaheinm** [openpracticelibrary/opl-api-gateway#3]
As a media service, I need files to pass through the api gateway to me, so that I can upload the file to storage.

ACCEPTANCE CRITERIA (as persona):
**Given** that I upload a file through the api gateway,
**When** the api gateway accesses the media service schema,
**Then** the file being uploaded should be passed to the media service

NOTES:
https://github.com/apollographql/apollo-server/issues/3033

BLOCKERS:
None

**Comment by omcneil** [comment]
Closing issue, no longer needed
